# Generated by Django 3.0.6 on 2020-05-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=9)),
                ('phone_number', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LocalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthdate', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Local')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Particular')),
            ],
        ),
        migrations.AddField(
            model_name='particular',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.User'),
        ),
        migrations.AddField(
            model_name='local',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.LocalType'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Local')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Particular')),
            ],
        ),
    ]
