# Generated by Django 3.0.6 on 2020-05-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamtours_app', '0002_particular_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='particular',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
