# Generated by Django 3.0.6 on 2020-05-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamtours_app', '0003_auto_20200524_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='local',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Local'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='particular',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Particular'),
        ),
    ]
