# Generated by Django 3.0.6 on 2020-05-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamtours_app', '0004_auto_20200525_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Local'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='particular',
            field=models.ForeignKey(db_column='dreamtours_app_particular', on_delete=django.db.models.deletion.CASCADE, to='dreamtours_app.Particular'),
        ),
    ]
